# This is a basic workflow to help you get started with Actions

name: Artifact Practice

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  artifact-demo:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Step 1: Check out the repository
      - name: Check out repository
        uses: actions/checkout@v4

      # Step 2: Create a file to upload as an artifact
      - name: Create a sample artifact file
        run: |
          echo "This is a sample artifact file." > sample-artifact.txt
          mkdir -p artifacts
          echo "Another file in a folder." > artifacts/another-file.txt

      # Step 3: Upload the artifact
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: my-artifact
          path: |
            sample-artifact.txt
            artifacts/

      # Step 4: Download the artifact (for demonstration purposes)
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: my-artifact
          path: downloaded-artifacts

      # Step 5: List downloaded files
      - name: List downloaded files
        run: ls -R downloaded-artifacts
